//EXERCISES
export const CREATE_EXERCISE = 'CREATE_EXERCISE';
export const UPDATE_EXERCISE = 'UPDATE_EXERCISE';
export const DELETE_EXERCISE = 'DELETE_EXERCISE';
export const FETCH_ALL_EXERCISES = 'FETCH_ALL_EXERCISES';


//NUTRITION
export const CREATE_RECIPE = 'CREATE_RECIPE';
export const UPDATE_RECIPE = 'UPDATE_RECIPE';
export const DELETE_RECIPE = 'DELETE_RECIPE';
export const FETCH_ALL_NUTRITION = 'FETCH_ALL_NUTRITION';


//AUTH
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
